services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
    ports:
      - "5532:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
